### ISSUE TITLE
Can't save home page attributes because it thinks you're trying to save a slug when actually you're not

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog-mothership-cms#214]
#### Bug description
When trying to save the home page attributes, you get this lovely little error message:
![screen shot 2014-07-22 at 16 31 25](https://cloud.githubusercontent.com/assets/4520924/3660218/533ecfb0-11b5-11e4-87cd-913be992b480.png)

I think it's because of this:
![screen shot 2014-07-22 at 16 30 22](https://cloud.githubusercontent.com/assets/4520924/3660222/58f67f52-11b5-11e4-9ea9-938e09e2ae17.png)

#### How can this be replicated?
Edit the home page of a Mothership site. Specifically, I was trying to add a tag to the home page

**Comment by kuiche** [comment]
This is now fixed
